// <auto-generated />
using System;
using HMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMS.Migrations
{
    [DbContext(typeof(HMSDbContext))]
    [Migration("20260326004259_UpdateonMedicalRecordEntity")]
    partial class UpdateonMedicalRecordEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HMS.Data.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 3, 21, 2, 42, 58, 539, DateTimeKind.Local).AddTicks(4632),
                            DoctorId = 1,
                            Notes = "Checkup",
                            PatientId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 3, 23, 2, 42, 58, 539, DateTimeKind.Local).AddTicks(4679),
                            DoctorId = 1,
                            Notes = "Follow-up",
                            PatientId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2026, 3, 27, 2, 42, 58, 539, DateTimeKind.Local).AddTicks(4682),
                            DoctorId = 4,
                            Notes = "New Patient",
                            PatientId = 4,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 3, 28, 2, 42, 58, 539, DateTimeKind.Local).AddTicks(4685),
                            DoctorId = 2,
                            Notes = "Vaccination",
                            PatientId = 3,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2026, 3, 25, 2, 42, 58, 539, DateTimeKind.Local).AddTicks(4688),
                            DoctorId = 5,
                            Notes = "Routine check",
                            PatientId = 5,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2026, 4, 5, 2, 42, 58, 539, DateTimeKind.Local).AddTicks(4690),
                            DoctorId = 5,
                            Notes = "Monthly review",
                            PatientId = 3,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 3, 6, 2, 42, 58, 539, DateTimeKind.Local).AddTicks(4692),
                            DoctorId = 3,
                            Notes = "Post-surgery",
                            PatientId = 2,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("HMS.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cardiology (القلب)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pediatrics (الأطفال)"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Orthopedics (العظام)"
                        });
                });

            modelBuilder.Entity("HMS.Data.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "ahmed@hms.com",
                            Name = "Dr. Ahmed Mansour",
                            Salary = 45000m,
                            Specialization = "Consultant"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "mona@hms.com",
                            Name = "Dr. Mona Abdel-Aziz",
                            Salary = 38000m,
                            Specialization = "Surgeon"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "tarek@hms.com",
                            Name = "Dr. Tarek El-Shennawy",
                            Salary = 42000m,
                            Specialization = "Specialist"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "khaled@hms.com",
                            Name = "Dr. Khaled Hassan",
                            Salary = 40000m,
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Email = "fatma@hms.com",
                            Name = "Dr. Fatma El-Zahraa",
                            Salary = 37000m,
                            Specialization = "Pediatrician"
                        });
                });

            modelBuilder.Entity("HMS.Data.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagnosis = "Hypertension",
                            LastUpdated = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            Treatment = "Meds"
                        },
                        new
                        {
                            Id = 2,
                            Diagnosis = "ACL Repair",
                            LastUpdated = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            Treatment = "PT"
                        },
                        new
                        {
                            Id = 3,
                            Diagnosis = "Seasonal Allergy",
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 4,
                            Treatment = "Antihistamines"
                        });
                });

            modelBuilder.Entity("HMS.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1985, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "m.youssef@gmail.com",
                            FullName = "Mohamed Youssef El-Sherif"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1992, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.m88@yahoo.com",
                            FullName = "Sara Mahmoud Ibrahim"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2015, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.fayoumy@outlook.com",
                            FullName = "Omar Khaled El-Fayoumy"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1990, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "layla.a@gmail.com",
                            FullName = "Layla Ahmed Mahmoud"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1978, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hassan.ali@gmail.com",
                            FullName = "Hassan Ali Mansour"
                        });
                });

            modelBuilder.Entity("HMS.Data.Models.PatientPhones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientPhones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PatientId = 1,
                            PhoneNumber = "01012345678"
                        },
                        new
                        {
                            Id = 2,
                            PatientId = 1,
                            PhoneNumber = "01198765432"
                        },
                        new
                        {
                            Id = 3,
                            PatientId = 2,
                            PhoneNumber = "01255544433"
                        },
                        new
                        {
                            Id = 4,
                            PatientId = 3,
                            PhoneNumber = "01500011122"
                        },
                        new
                        {
                            Id = 5,
                            PatientId = 4,
                            PhoneNumber = "01099988877"
                        },
                        new
                        {
                            Id = 6,
                            PatientId = 5,
                            PhoneNumber = "01122233344"
                        });
                });

            modelBuilder.Entity("HMS.Data.Models.Appointment", b =>
                {
                    b.HasOne("HMS.Data.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HMS.Data.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HMS.Data.Models.Doctor", b =>
                {
                    b.HasOne("HMS.Data.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HMS.Data.Models.MedicalRecord", b =>
                {
                    b.HasOne("HMS.Data.Models.Patient", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("HMS.Data.Models.MedicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HMS.Data.Models.PatientPhones", b =>
                {
                    b.HasOne("HMS.Data.Models.Patient", null)
                        .WithMany("Phones")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HMS.Data.Models.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HMS.Data.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HMS.Data.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
